development:
  adapter: postgresql
  encoding: unicode
  database: tasting_notes_development
  pool: 5
  username: DawnMariah  
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: tasting_notes_test
  pool: 5
  username: DawnMariah
  password: 